<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <!--        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>-->
        <NoWarn>MSB3270</NoWarn>
        <DebugType>portable</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="OuterWildsGameLibs" Version="1.1.16.1372" ExcludeAssets="runtime" />
        <PackageReference Include="MessagePack" Version="3.1.4" ExcludeAssets="runtime"/> <!--fixes ArrayPool error with publicizer being weird-->
    </ItemGroup>
</Project>
